version: '3.8'
services:
  mc-smoe:
    image: wazenmai/expert-sparsity:latest
    build:
      context: .
    container_name: expert-sparsity
    volumes:
      - /home/wazenmai/Warehouse/NLP/huggingface:/app/warehouse/huggingface
      - /home/wazenmai/Warehouse/NLP/checkpoints/prune_expert_baseline/:/app/results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      HF_HOME: "/app/warehouse/huggingface"
      NCCL_P2P_DISABLE: "1"
      TOKENIZERS_PARALLELISM: "false"
    command:
      - bash
      - my_run.sh
      
          